[package]
name = "Test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-files = "0.6"
reqwest = { version = "0.11", features = ["blocking"] }

[[bench]]
name = "bench"
harness = false